## This is for development ONLY. DO NOT USE THIS IN PRODUCTION!

version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=spatch
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 9000:80
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=password
  tomcat:
    container_name: tomcat
    image: tomcat:8
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 8888:8080
    volumes:
      - ./logs/tomcat:/usr/local/tomcat/logs
      - ./target/api.war:/usr/local/tomcat/webapps/api.war
