version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 9000:80
    environment:
      - PMA_HOST=mariadb
  tomcat:
    container_name: tomcat
    image: tomcat:8
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 8888:8080
    volumes:
      - ./data/tomcat/webapps:/usr/local/tomcat/webapps
      - ./logs/tomcat:/usr/local/tomcat/logs
